name: Deploy Eyrie
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Create a glob and deploy latest to ~wannec-dozzod-marzod (devstream)"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.JANEWAY_SERVICE_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Build Frontend
        working-directory: ./ui
        run: | 
          npm ci
          npm run build
      - id: glob
        uses: ./.github/actions/glob
        with:
          folder: 'ui/dist/*'
          docket: 'desk/desk.docket-0'
      - name: Commit and Push Glob
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add desk/desk.docket-0
          git commit -n -m "update glob: ${{ steps.glob.outputs.hash }} [skip actions]" || echo "No changes to commit"
          git pull origin master --rebase --autostash
          git push
      - id: deploy
        name: Deploy
        run:
          ./.github/helpers/deploy.sh tloncorp/eyrie eyrie wannec-dozzod-marzod us-west1-b
        env:
          SSH_SEC_KEY: ${{ secrets.JANEWAY_SSH_SEC_KEY }}
          SSH_PUB_KEY: ${{ secrets.JANEWAY_SSH_PUB_KEY }}